[server]
port = 8503
enableCORS = false
headless = true
enableXsrfProtection = false
watchFiles = false   # add this line

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
