[server]
enableCORS = false
headless = true
enableXsrfProtection = false
# port = 8503    # remove this line

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
